on:
  workflow_dispatch: {}

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install
      - run: yarn run deploy
        
