on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        options:
          - "patch"
          - "minor"
          - "major"
        description: Bump version type


env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install
      - run: git config user.name ${{ github.actor }} && git config user.email  ${{ github.actor }}@users.noreply.github.com
      - run: npm version ${{ inputs.release_type }} && git push --tags
      - run: yarn run deploy
